- name: This is test playbook
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: Show manageiq object
      debug:
        msg: "{{ manageiq }}"

    - name: Register VM IP Addresses
      set_fact:
        vm_app_ip: "10.0.0.11"
        vm_db_ip: "10.0.0.12"

    - debug: var=vm_app_ip
    - debug: var=vm_db_ip


    - name: Create in Mem inventory
      add_host:
        name: "{{ vm_app_ip }}"
        name: "{{ vm_db_ip }}"
