- name: This is test playbook
  hosts: localhost
  gather_facts: true
#  connection: local

#  vars:
#    wait_for_ssh: False
#    provider_id: "{{ provider_id }}"
#    max_retries: 9
#    retry_interval: 20

  tasks:
    - name: Show manageiq object
      debug:
        msg: "{{ manageiq }}"

    - name: Show manageiq object
      debug:
        msg: "{{ manageiq }}"
